prlp.settings:
  type: mapping
  label: 'PRLP module settings'
  mapping:
    password_required:
      type: boolean
      label: 'Password Required'
    login_destination:
      type: string
      label: 'Login Destination'
