queue_mail.settings:
  type: config_object
  label: 'Queue mail settings'
  mapping:
    queue_mail_keys:
      type: string
      label: 'Mail IDs to queue'
    queue_mail_queue_time:
      type: integer
      label: 'Queue processing time (max)'
    queue_mail_queue_wait_time:
      type: integer
      label: 'Wait time per item'
    threshold:
      type: integer
      label: 'Queue retry threshold'
    requeue_interval:
      type: integer
      label: 'Requeue interval'
