password_strength.settings:
  type: config_object
  label: 'Password Strength settings'
  mapping:
    enabled_matchers:
      type: mapping
      label: 'enabled_matchers'
      mapping:
        zxcvbn_datematch:
          type: string
          label: 'zxcvbn_datematch'
        zxcvbn_digitmatch:
          type: string
          label: 'zxcvbn_digitmatch'
        zxcvbn_l33tmatch:
          type: string
          label: 'zxcvbn_l33tmatch'
        zxcvbn_repeatmatch:
          type: string
          label: 'zxcvbn_repeatmatch'
        zxcvbn_sequencematch:
          type: string
          label: 'zxcvbn_sequencematch'
        zxcvbn_spatialmatch:
          type: string
          label: 'zxcvbn_spatialmatch'
        zxcvbn_yearmatch:
          type: string
          label: 'zxcvbn_yearmatch'
        zxcvbn_dictionarymatch:
          type: string
          label: 'zxcvbn_dictionarymatch'

password_policy.constraint.plugin.password_strength_constraint:
  type: password_policy.constraint.plugin
  mapping:
    strength_score:
      type: integer
